---
- name: ensure fail2ban is installed
  apt: name=fail2ban state=present
  when: ansible_distribution == "Debian"

- name: ensure fail2ban is running
  service: name=fail2ban enabled=yes state=started

- name: ensure netfilter-persistent is installed
  apt: name=netfilter-persistent state=present
  when: ansible_distribution == "Debian"

- name: ensure curl is installed
  apt: name=curl state=present
  when: ansible_distribution == "Debian"

- name: update jail.conf (Debian8)
  template:
    src: template/jail.conf.j2
    dest: /etc/fail2ban/jail.conf
    owner: root
    group: root
    mode: 0644
  register: fail2ban
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

- name: update jail.d/default.conf (Debian9)
  template:
    src: template/jail.d/default.conf.j2
    dest: /etc/fail2ban/jail.d/default.conf
    owner: root
    group: root
    mode: 0644
  register: fail2ban
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9"

- name: update jail.d/sshd.conf (Debian9)
  template:
    src: template/jail.d/sshd.conf.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: root
    group: root
    mode: 0644
  register: fail2ban
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9"

- name: restart fail2ban
  service: name=fail2ban state=restarted
  when: fail2ban.changed

